
name: Build and Push Custom Backend Images to Docker Hub
on:
  push:
    branches:
      - main


jobs:
  build-and-push: #job: 1 Build and Push Images
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend push
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coverage-grader-backend:latest
          no-cache: true
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21098
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker compose -f docker-compose.yml -f docker-compose.prod.yml pull coverage-app-2 queue-worker scheduler
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --force-recreate --no-deps coverage-app-2 queue-worker scheduler
            echo "Running database migrations..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml exec coverage-app-2 php artisan migrate --force
            docker image prune -f

